name: halcyon

services:
    halcyon-vite:
        image: halcyon-vite:dev
        build:
            context: .
            target: dev
            args:
                VERSION: 1.0.0-docker
        command: npm run dev -- --host=0.0.0.0 --port=5173
        environment:
            USE_POLLING: true
            API_URL: http://localhost:5257
        ports:
            - 5173:5173
        volumes:
            - ./src:/app/src
            - ./public:/app/public

    halcyon-api:
        image: ghcr.io/chrispoulter/halcyon-api:latest
        environment:
            ConnectionStrings__Database: Host=host.docker.internal;Port=5432;Database=halcyon;Username=postgres;Password=password
            ConnectionStrings__RabbitMq: amqp://guest:guest@host.docker.internal:5672
            ConnectionStrings__Redis: host.docker.internal
            Email__SmtpServer: host.docker.internal
            Serilog__WriteTo__Seq__Args__serverUrl: http://host.docker.internal:5341
            Serilog__MinimumLevel__Override__Microsoft.AspNetCore.DataProtection: Error
        ports:
            - 5257:8080
            - 7257:8081
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy

    postgres:
        image: postgres:17.0
        user: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 3

    rabbitmq:
        image: rabbitmq:4.0-management
        hostname: local
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        restart: always
        healthcheck:
            test: ['CMD', 'rabbitmqctl', 'status']
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:7.4
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        restart: always
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 3

    maildev:
        image: maildev/maildev:2.1.0
        environment:
            MAILDEV_MAIL_DIRECTORY: /tmp
        ports:
            - 1025:1025
            - 1080:1080
        volumes:
            - maildev:/tmp
        restart: always

    seq:
        image: datalust/seq:2024.3
        environment:
            ACCEPT_EULA: Y
            SEQ_API_CANONICALURI: http://localhost:5341
        ports:
            - 5341:80
        volumes:
            - seq:/data
        restart: always

volumes:
    postgres:
        name: halcyon-postgres
    rabbitmq:
        name: halcyon-rabbitmq
    redis:
        name: halcyon-redis
    maildev:
        name: halcyon-maildev
    seq:
        name: halcyon-seq
